### ISSUE TITLE
Warping Error Compuation issue 

### ISSUE THREAD

**Issue by CIntellifusion** [evalcrafter/EvalCrafter#15]
Hi, thanks for your excellent work. 

I notice you have comment this line : https://github.com/evalcrafter/EvalCrafter/blob/6dd627a8ac48ab1d4081ffc1abaca6704ea59c43/metrics/RAFT/optical_flow_scores.py#L28, which is import warp_utils. 

But the warp_utils.detect_occlusion is used in this file. When I uncomment this line, it tells Fail to import Resample2D_cuda 

I was wondering is it necessary to use warp_utils? or there is a work around.

**Comment by Yaofang-Liu** [comment]
Yes, warp_utils is needed. To use that, you should compile Resample2D_cuda beforehand. I've updated the README.md file to include: 
> cd ./metrics/RAFT/networks/resample2d_package
> python setup.py install --user
> Note that if you encounter this problem RuntimeError: GET was unable to find an engine to execute this computation when running the evaluation code, you may update Cuda to version Cuda 11.7 (Compatibility issue). 

Very sorry for the confusion caused!

**Comment by CIntellifusion** [comment]
Thanks for your reply. But I found there is still a problem. 

]`
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.`


Do you have any other solutions or workarounds?  I  was wondering there might be a standard torch implementation or even naive cpu version. Thanks for your help.

**Comment by Yaofang-Liu** [comment]
Hi, I am not sure what problem you got, the installation for resample2d_cuda could be troublesome. You may ref to https://github.com/NVIDIA/flownet2-pytorch for installation, which also includes may solutions in its issues page.

**Comment by CIntellifusion** [comment]
Thanks for your reply. But I have solved this issue by specify cuda version to 11.7.
`
export PATH=/usr/local/cuda-11.7/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.7/lib64:$LD_LIBRARY_PATH
`
